# Generated by Django 2.2.6 on 2019-10-23 05:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0003_auto_20191023_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(default=None, max_length=255)),
                ('title_2', models.CharField(default=None, max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1920, 520], upload_to='slider')),
                ('link', models.CharField(default=None, max_length=255)),
                ('created_date', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
                ('modified_date', models.DateField(default=None)),
                ('modified_by', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='status',
            field=models.CharField(choices=[('AC', 'active'), ('IN', 'inactive')], default='AC', max_length=8),
        ),
    ]
