# Generated by Django 2.2.6 on 2019-10-23 05:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0004_auto_20191023_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 520], upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
