# Generated by Django 2.2.6 on 2019-10-23 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0005_auto_20191023_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(choices=[('AC', 'active'), ('IN', 'inactive')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
