# Generated by Django 2.2.6 on 2019-10-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0007_adminuser_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='created_date',
        ),
    ]
