# Generated by Django 2.2.6 on 2019-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0008_auto_20191023_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='created_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
    ]
