# Generated by Django 2.2.6 on 2019-10-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0009_auto_20191023_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='created_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
