# Generated by Django 2.2.6 on 2019-10-23 06:42

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0010_auto_20191023_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(default=None, max_length=255)),
                ('title_2', models.CharField(default=None, max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1920, 520], upload_to='slider')),
                ('link', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(default=None, verbose_name=datetime.date(2019, 10, 23))),
                ('created_by', models.DateField(default=None)),
                ('modified_date', models.DateField(default=None, verbose_name=datetime.date(2019, 10, 23))),
                ('modified_by', models.DateField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_date',
            field=models.DateField(default=None, verbose_name=datetime.date(2019, 10, 23)),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(default='active', max_length=8),
        ),
    ]
