# Generated by Django 2.2.6 on 2019-10-23 13:37

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0012_auto_20191023_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField(default=None)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[540, 293], upload_to='about')),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_date',
            field=models.DateField(default=None),
        ),
    ]
