# Generated by Django 2.2.6 on 2019-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0013_auto_20191023_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
