# Generated by Django 2.2.6 on 2019-10-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0014_auto_20191024_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
