# Generated by Django 2.2.6 on 2019-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0016_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
