# Generated by Django 2.2.6 on 2019-10-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0017_auto_20191024_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='about',
            name='created_date',
            field=models.DateField(default=None),
        ),
    ]
