# Generated by Django 2.2.6 on 2019-10-24 09:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0019_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='pin_code',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[150, 150], upload_to='user_profile'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
