# Generated by Django 2.2.6 on 2019-10-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0021_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='map_address2',
        ),
    ]
