# Generated by Django 2.2.6 on 2019-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0022_remove_contactus_map_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='created_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='modified_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='modified_date',
            field=models.DateField(default=None),
        ),
    ]
