# Generated by Django 2.2.6 on 2019-10-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0023_auto_20191024_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactUs',
        ),
    ]
