# Generated by Django 2.2.6 on 2019-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0024_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('map_address', models.TextField(default=None)),
                ('footer_content', models.TextField()),
                ('created_date', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
            ],
        ),
    ]
