# Generated by Django 2.2.6 on 2019-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0026_valuablecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactus',
            name='contact_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='land_line_number',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
