# Generated by Django 2.2.6 on 2019-10-25 06:32

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0027_auto_20191024_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.IntegerField(default=None)),
                ('sub_category', models.IntegerField(default=None)),
                ('category_name', models.CharField(max_length=255)),
                ('category_slug', models.CharField(max_length=255)),
                ('category_image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[250, 250], upload_to='category')),
                ('category_status', models.CharField(default='active', max_length=8)),
                ('description', models.TextField(default=None)),
                ('category_commission_fixed', models.CharField(default=None, max_length=255)),
                ('category_commission_percent', models.CharField(default=None, max_length=255)),
                ('category_meta_title', models.CharField(default=None, max_length=255)),
                ('category_meta_description', models.TextField(default=None)),
                ('category_meta_keyword', models.CharField(default=None, max_length=255)),
                ('created_date', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
                ('modified_date', models.DateField(default=None)),
                ('modified_by', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
                ('modified_date', models.DateField(default=None)),
                ('modified_by', models.IntegerField(default=None)),
            ],
        ),
    ]
