# Generated by Django 2.2.6 on 2019-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0029_remove_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
                ('modified_date', models.DateField(default=None)),
                ('modified_by', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_commission_fixed',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_commission_percent',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
