# Generated by Django 2.2.6 on 2019-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0030_auto_20191025_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_commission_fixed',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_commission_percent',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
