# Generated by Django 2.2.6 on 2019-10-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0031_auto_20191025_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modified_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
