# Generated by Django 2.2.6 on 2019-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0032_auto_20191025_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
