# Generated by Django 2.2.6 on 2019-10-25 07:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0034_auto_20191025_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[540, 293], upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='pin_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[150, 150], upload_to='user_profile'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='footer_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='land_line_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='map_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[600, 600], upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 520], upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='customer_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[100, 100], upload_to='valuable_customer'),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
