# Generated by Django 2.2.6 on 2019-10-25 09:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0035_auto_20191025_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('brand_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[130, 80], upload_to='brand')),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
