# Generated by Django 2.2.6 on 2019-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0036_auto_20191025_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.TextField(null=True)),
                ('return_policy', models.TextField(null=True)),
                ('terms_of_use', models.TextField(null=True)),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
            ],
        ),
    ]
