# Generated by Django 2.2.6 on 2019-10-26 06:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0037_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(null=True)),
                ('brand_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_slug', models.CharField(max_length=255, null=True)),
                ('product_desc', models.TextField(null=True)),
                ('compositions', models.CharField(max_length=255, null=True)),
                ('styles', models.CharField(max_length=255, null=True)),
                ('properties', models.CharField(max_length=255, null=True)),
                ('available_qty', models.IntegerField(null=True)),
                ('mrp', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('net_price', models.FloatField(null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_keyword', models.CharField(max_length=255, null=True)),
                ('meta_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('product_list', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[229, 188], upload_to='product_list')),
                ('product_details', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[600, 600], upload_to='product_details')),
                ('download_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[300, 400], upload_to='download_image')),
                ('created_date', models.DateField(null=True)),
                ('modifiedd_date', models.DateField(null=True)),
            ],
        ),
    ]
