# Generated by Django 2.2.6 on 2019-10-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0038_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='mrp_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='net_price',
            new_name='sell_price',
        ),
    ]
