# Generated by Django 2.2.6 on 2019-10-29 05:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0039_auto_20191026_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_download_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('download_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[300, 400], upload_to='product_download_image')),
                ('created_date', models.DateField(null=True)),
                ('modifiedd_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='download_image',
        ),
    ]
