# Generated by Django 2.2.6 on 2019-10-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0043_auto_20191029_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product_details',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='product_list',
        ),
        migrations.AddField(
            model_name='product_image',
            name='product',
            field=models.ImageField(null=True, upload_to='test_product'),
        ),
    ]
