# Generated by Django 2.2.6 on 2019-10-30 05:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0044_auto_20191030_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.AddField(
            model_name='product_image',
            name='product_details',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[600, 600], upload_to='product_details'),
        ),
        migrations.AddField(
            model_name='product_image',
            name='product_list',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[229, 188], upload_to='product_list'),
        ),
    ]
