# Generated by Django 2.2.6 on 2019-10-30 05:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0045_auto_20191030_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image_resize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', imagekit.models.fields.ProcessedImageField(upload_to='test_product_list')),
                ('product_details', imagekit.models.fields.ProcessedImageField(upload_to='test_product_details')),
                ('created_date', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
            ],
        ),
    ]
