# Generated by Django 2.2.6 on 2019-10-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0046_product_image_resize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image_resize',
            name='product_details',
            field=models.ImageField(null=True, upload_to='test_product_details'),
        ),
        migrations.AlterField(
            model_name='product_image_resize',
            name='product_list',
            field=models.ImageField(null=True, upload_to='test_product_list'),
        ),
    ]
