# Generated by Django 2.2.6 on 2019-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0047_auto_20191030_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_download_image',
            name='download_image',
            field=models.ImageField(null=True, upload_to='product_download_image'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product_details',
            field=models.ImageField(null=True, upload_to='product_details'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product_list',
            field=models.ImageField(null=True, upload_to='product_list'),
        ),
    ]
