# Generated by Django 2.2.6 on 2019-10-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0048_auto_20191031_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_image_resize',
        ),
    ]
