# Generated by Django 2.2.6 on 2019-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0049_delete_product_image_resize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
    ]
