# Generated by Django 2.2.6 on 2019-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0050_auto_20191031_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(default='active', max_length=8),
        ),
    ]
