# Generated by Django 2.2.6 on 2019-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0051_brand_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('cart_item_id', models.IntegerField(null=True)),
                ('cart_session_id', models.CharField(max_length=256, null=True)),
                ('cart_mrp_price', models.FloatField(null=True)),
                ('cart_discount', models.FloatField(null=True)),
                ('cart_sell_price', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='about'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='valuablecustomer',
            name='customer_image',
            field=models.ImageField(null=True, upload_to='valuable_customer'),
        ),
    ]
