# Generated by Django 2.2.6 on 2019-10-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0052_auto_20191031_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='user_profile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category'),
        ),
    ]
