# Generated by Django 2.2.6 on 2019-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0054_auto_20191031_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, null=True)),
                ('title_2', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('banner_image', models.ImageField(null=True, upload_to='banner')),
                ('banner_type', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
            ],
        ),
    ]
