# Generated by Django 2.2.6 on 2019-11-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0055_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
