# Generated by Django 2.2.6 on 2019-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0056_banner_title_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
            ],
        ),
    ]
