# Generated by Django 2.2.6 on 2019-11-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0058_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countries',
        ),
    ]
