# Generated by Django 2.2.6 on 2019-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0059_delete_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('created_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('deli_address_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('alt_mobile_number', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('address_type', models.CharField(default='home', max_length=8)),
                ('is_default', models.CharField(default='no', max_length=8)),
                ('post_office', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateField(null=True)),
                ('created_by', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('modified_by', models.DateField(null=True)),
            ],
        ),
    ]
