# Generated by Django 2.2.6 on 2019-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0061_auto_20191104_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('created_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(max_length=256, null=True)),
                ('order_track_id', models.CharField(max_length=256, null=True)),
                ('order_customer_id', models.IntegerField(null=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_sub_total_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_shipping_charge', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_status', models.CharField(default='Pending', max_length=20)),
                ('payment_method', models.CharField(default='cod', max_length=8)),
                ('payment_status', models.CharField(default='unpaid', max_length=8)),
                ('order_created_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('order_product_id', models.IntegerField(null=True)),
                ('product_seller_id', models.IntegerField(null=True)),
                ('order_product_mrp', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_product_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_product_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_product_qty', models.IntegerField(null=True)),
                ('order_product_status', models.CharField(default='Pending', max_length=20)),
                ('order_created_date', models.DateField(null=True)),
            ],
        ),
    ]
