# Generated by Django 2.2.6 on 2019-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0063_adminuser_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
    ]
