# Generated by Django 2.2.6 on 2019-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0067_auto_20191107_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='remaining_rating',
            field=models.IntegerField(null=True),
        ),
    ]
