# Generated by Django 2.2.6 on 2019-11-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0068_review_remaining_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
