# Generated by Django 2.2.6 on 2019-11-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0069_remove_review_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
