# Generated by Django 2.2.6 on 2019-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0070_auto_20191107_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
