# Generated by Django 2.2.6 on 2019-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0071_product_remaining_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('name', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('web_address', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_rating',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
