# Generated by Django 2.2.6 on 2019-11-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0072_auto_20191107_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_enquiry',
            old_name='name',
            new_name='full_name',
        ),
    ]
