# Generated by Django 2.2.6 on 2019-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0073_auto_20191107_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_enquiry',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
