# Generated by Django 2.2.6 on 2019-11-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0074_auto_20191107_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='cancel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='cancel_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='return_reason',
            field=models.TextField(null=True),
        ),
    ]
