# Generated by Django 2.2.6 on 2019-11-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0075_auto_20191108_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart_item',
            name='cart_session_id',
        ),
    ]
