# Generated by Django 2.2.6 on 2019-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0078_order_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='return_status',
            field=models.CharField(default='Rejected', max_length=20),
        ),
    ]
