# Generated by Django 2.2.6 on 2019-11-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0080_auto_20191119_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='return_status',
        ),
    ]
