# Generated by Django 2.2.6 on 2019-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0082_order_details_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_available',
            field=models.CharField(default='yes', max_length=8),
        ),
    ]
