# Generated by Django 2.2.6 on 2019-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0083_auto_20191120_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('payment_id', models.CharField(max_length=255, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('payment_date', models.DateField(null=True)),
            ],
        ),
    ]
