# Generated by Django 2.2.6 on 2019-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0084_online_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='pincode_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
