# Generated by Django 2.2.6 on 2019-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0085_pincode_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode_service',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
