# Generated by Django 2.2.6 on 2019-11-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0086_auto_20191122_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compositions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='product',
            name='styles',
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight_class',
            field=models.CharField(default='kg', max_length=10),
        ),
    ]
