# Generated by Django 2.2.6 on 2019-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0087_auto_20191122_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.TextField(null=True),
        ),
    ]
