# Generated by Django 2.2.6 on 2019-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0090_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.IntegerField(default=0),
        ),
    ]
