# Generated by Django 2.2.6 on 2019-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0091_auto_20191125_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_addon_cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('addon_item_id', models.IntegerField(null=True)),
                ('addon_item_sell_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
