# Generated by Django 2.2.6 on 2019-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0092_user_addon_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_addon_cart_item',
            name='cart_id',
            field=models.IntegerField(null=True),
        ),
    ]
