# Generated by Django 2.2.6 on 2019-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0093_user_addon_cart_item_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='addon_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('addon_product_id', models.IntegerField(null=True)),
                ('addon_product_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
