# Generated by Django 2.2.6 on 2019-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0094_addon_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart_item',
            name='addon_id_list',
            field=models.TextField(null=True),
        ),
    ]
