# Generated by Django 2.2.6 on 2019-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0095_user_cart_item_addon_id_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon_order',
            name='addon_product_id',
        ),
        migrations.AddField(
            model_name='addon_order',
            name='addon_product_id_list',
            field=models.TextField(null=True),
        ),
    ]
