# Generated by Django 2.2.6 on 2019-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0096_auto_20191203_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='addon_product_id_list',
            field=models.TextField(null=True),
        ),
    ]
