# Generated by Django 2.2.6 on 2019-12-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0100_auto_20191209_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='countries',
            new_name='country',
        ),
    ]
