# Generated by Django 2.2.6 on 2019-12-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0101_auto_20191209_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
