# Generated by Django 2.2.6 on 2019-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0106_auto_20191209_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='city',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='country',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
