# Generated by Django 2.2.6 on 2019-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debadmin', '0107_auto_20191210_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='city',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='country',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='city',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='country',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
