from .accounts import *
from .sliders import *
from .about import *
from .banner import *
from .gallery import *
from .contact import *
from .valuable_customer import *
from .category import *
from .brand import *
from .videos import *
from .faqs import *
from .policy import *
from .product import *
from .user_list import *
from .enquiry_list import *
from .order_list import *
from .deb_utility import *
from .pdf_generation import *
from .pincode_service import *